# -*- coding: utf-8 -*-
"""face_j1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvGQ3qYK4r8adqv-5tq0k_mSm0ARuUHs
"""

from matplotlib import pyplot as plt
import cv2

from re import X
image = cv2.imread("nima.jpg")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

model = cv2.CascadeClassifier("model.xml")
face = model.detectMultiScale(image=image, scaleFactor=1.2, minNeighbors=5, minSize=(30,30))

i = 0
while i < len(face):
  x = face[i][0]
  y = face[i][1]
  a = face[i][2]
  b = face[i][3]
  image = cv2.rectangle(image , (x,y) , (x+a,y+b) , (0,255,255))
  i = i + 1
plt.imshow(image)